"""audit logs

Revision ID: 218642d44fe7
Revises: 2ae92b6ef5ae
Create Date: 2026-07-22 18:35:11.268676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '218642d44fe7'
down_revision: Union[str, None] = '2ae92b6ef5ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('actor_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('target_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('channel_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('detail', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_created', 'audit_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
