"""channel bans

Revision ID: 2ae92b6ef5ae
Revises: f79431138ad6
Create Date: 2026-07-22 18:23:05.155977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae92b6ef5ae'
down_revision: Union[str, None] = 'f79431138ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_bans',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('channel_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('banned_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['banned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'user_id', name='uq_channel_ban')
    )
    op.create_index('ix_channel_ban_channel', 'channel_bans', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_channel_ban_channel', table_name='channel_bans')
    op.drop_table('channel_bans')
    # ### end Alembic commands ###
