"""message threads

Revision ID: 486f8bb61371
Revises: 218642d44fe7
Create Date: 2026-07-22 20:04:38.863878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '486f8bb61371'
down_revision: Union[str, None] = '218642d44fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('thread_root_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_messages_thread_root_id'), 'messages', ['thread_root_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'messages', ['thread_root_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_thread_root_id'), table_name='messages')
    op.drop_column('messages', 'thread_root_id')
    # ### end Alembic commands ###
