"""file uploads

Revision ID: ade2e03dbf06
Revises: edf6f290ef06
Create Date: 2026-07-23 10:49:47.691671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade2e03dbf06'
down_revision: Union[str, None] = 'edf6f290ef06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('uploader_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_image', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('messages', sa.Column('upload_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'messages', 'uploads', ['upload_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'upload_id')
    op.drop_table('uploads')
    # ### end Alembic commands ###
