"""user profiles and mentions

Revision ID: f79431138ad6
Revises: 07fe1b662c31
Create Date: 2026-07-22 17:25:55.678011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f79431138ad6'
down_revision: Union[str, None] = '07fe1b662c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_mentions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('message_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_mention')
    )
    op.create_index('ix_mention_message', 'message_mentions', ['message_id'], unique=False)
    op.create_index('ix_mention_user', 'message_mentions', ['user_id'], unique=False)
    # NOT NULL columns on an existing table need a server_default so existing
    # rows are backfilled; then drop the default to match the model (which
    # supplies '' from Python on insert).
    op.add_column(
        'users',
        sa.Column('bio', sa.String(length=500), nullable=False, server_default=''),
    )
    op.add_column(
        'users',
        sa.Column('pronouns', sa.String(length=40), nullable=False, server_default=''),
    )
    op.alter_column('users', 'bio', server_default=None)
    op.alter_column('users', 'pronouns', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pronouns')
    op.drop_column('users', 'bio')
    op.drop_index('ix_mention_user', table_name='message_mentions')
    op.drop_index('ix_mention_message', table_name='message_mentions')
    op.drop_table('message_mentions')
    # ### end Alembic commands ###
